### ISSUE TITLE
파이썬 정복하기

### ISSUE THREAD

**Issue by hyunolike** [hyunolike/quiz_archives#1]
- [x] 파이썬 기초 문법
- [ ] 파이썬 고급 문법
- [ ] 파이썬 문제풀이
- [ ] 모의 테스트 진행
